### PR TITLE
HW2_1 

### PR DESCRIPTION
**Pull request by rittata**

### CODE REVIEW

**Comment by rittata** [comment]
Hello @rinnifox, please review the first part of the HW2.

**Comment by rinnifox** [comment]
Hi Margarita!

Several comments regarding your homework.

1. The regular expressions are not fully correct. 
 - For Uniprot, I shared the link in the lecture materials how to properly construct it, as this one is pretty much difficult to complete yourself. Since you are checking only the first element of the list, you do not see that in fact the second element `Q91XI3` won't match the expression you've written. If you change the order of element, you will be able to see that. So checking the first element only is correct in assumption that all the IDs are from the same database but you are not accounting for possible mistakes and typos though.
 - For ENSEMBL, you should check this [link](https://www.ensembl.org/info/genome/stable_ids/prefixes.html) - it explains how the ENSEMBL ID is composed. Currently, your expression allows **any** amount of letters after `ENS`, which is not correct. There are two main things to note: 1) Feature prefix (1 or 2 symbols indicating the type of the sequence); 2) Species (nothing for human and a three or four-letter code for other ones; let's not concentrate on rare mice cases like MGP_AKRJ_). Using this, you should be able to create more precise expression to filter ENSEMBL codes. 
2.  I see you've used Colab for writing the code. It is ok, but when compiling a final python file, you have to keep in mind that pieces of code like this do not make any sense:
```
parsed_data = parse_response_ensembl(response)
parsed_data
```
First, to make it work, you have to directly print it as you are doing it later in another piece of code. Second,  since it is some intermediate testing, if you want to keep this in your code, it is better to add some text output, e.g. `print('Testing parsed data for parse)response_ensembl', parsed_data)`, but in principle it is not necessary since you're doing just the same in the end of your file. So it is up to you either to provide some text around it or just to remove/comment these lines of code.

Fix this please by the next lecture, ok?

**Comment by rinnifox** [comment]
UPD.

> 2) Species (nothing for human and a three or FOUR-letter code for other ones;

**Comment by rittata** [comment]
Hi @rinnifox, thank you for the detailed comment! I've fixed the issues, hopefully this version is ok.

**Comment by rinnifox** [comment]
Hi Margarita!

Great, you can merge now this PR by yourself!

**Pull request merged**
